title: Tech Programmer at Massive Entertainment
subtitle: Working on Avatar, Frontiers of Pandora
start_date: '2017-01-01'
end_date: '2019-07-31'
tech: C++, Snowdrop
image_layout: featured
github_url:
live_url: https://www.massive.se/project/avatar-frontiers-of-pandora/

description: |
  I worked on the tech team for Avatar project for Ubisoft.
  I worked on implementing and maintaining tech features for the in house Snowdrop Engine.

  Some of the tech I worked on are the impostor system for tree rendering, a GI low res fallback system, fog and atmospheric effects and shaders. Tech art tools, etc....

  In that job I worked closely with tech programmers in my team, in other developers using Snowdrop on other projects, as well as tech artists.